# Linear queue for the main branch.
queue_rules:
  - name: main
    conditions:
      - base=master
      # Require integration tests before merging only
      - or:
          - check-success=integration-test-result
          - check-neutral=integration-test-result
          - check-skipped=integration-test-result

pull_request_rules:
  - name: merge to master
    conditions:
      - base=master
      - label=automerge:no-update
      - or:
          - '#commits-behind=0'
          - label=bypass:linear-history
      - or:
          - check-success=wait-integration-pre-checks
          - label=bypass:integration
      - or:
          - and: # breakage succeeds like we thought
              - check-success=breakage
              - -label=proto:expect-breakage
          - and: # breakage fails like we thought
              - check-failure=breakage
              - label=proto:expect-breakage
    actions:
      queue:
        name: main
        method: merge
  - name: rebase updates then merge to master
    conditions:
      - base=master
      - label=automerge:rebase
      - or:
          - check-success=wait-integration-pre-checks
          - label=bypass:integration
      - or:
          - and: # breakage succeeds like we thought
              - check-success=breakage
              - -label=proto:expect-breakage
          - and: # breakage fails like we thought
              - check-failure=breakage
              - label=proto:expect-breakage
    actions:
      queue:
        name: main
        method: merge
        update_method: rebase
  - name: squash to master
    conditions:
      - base=master
      - label=automerge:squash
      - or:
          - check-success=wait-integration-pre-checks
          - label=bypass:integration
      - or:
          - and: # breakage succeeds like we thought
              - check-success=breakage
              - -label=proto:expect-breakage
          - and: # breakage fails like we thought
              - check-failure=breakage
              - label=proto:expect-breakage
    actions:
      queue:
        name: main
        method: squash
